import { useRef, useEffect } from "react";
import ReactMarkdown from "react-markdown";

interface PrintableResumeProps {
  content: string;
  targetId: string;
}

export function PrintableResume({ content, targetId }: PrintableResumeProps) {
  return (
    <div id={targetId} className="bg-white text-black p-[20mm] max-w-[210mm] mx-auto min-h-[297mm] shadow-none">
      <style>{`
        @media print {
          body {
            background: white;
            color: black;
          }
          @page {
            margin: 0;
            size: auto;
          }
          .no-print {
            display: none !important;
          }
        }
        #${targetId} {
          font-family: 'Times New Roman', Times, serif;
          line-height: 1.3;
          font-size: 10pt;
        #${targetId} h1 {
          font-size: 18pt;
          font-weight: bold;
          border-bottom: 2px solid #000;
          padding-bottom: 1px;
          margin-bottom: 6px;
          text-transform: uppercase;
        }
        #${targetId} h2 {
          font-size: 13pt;
          font-weight: bold;
          border-bottom: 1px solid #ccc;
          padding-bottom: 1px;
          margin-top: 10px;
          margin-bottom: 4px;
          text-transform: uppercase;
          color: #333;
        }
        #${targetId} h3 {
          font-size: 10pt;
          font-weight: bold;
          margin-top: 6px;
          margin-bottom: 1px;
        }
        #${targetId} p {
          margin-bottom: 4px;
          text-align: justify;
        }
        #${targetId} ul {
          margin-left: 12px;
          margin-bottom: 4px;
          list-style-type: disc;
        }
        #${targetId} li {
          margin-bottom: 1px;
        }
        /* Specific Markdown Override */
        #${targetId} strong {
          font-weight: bold;
        }
      `}</style>

      {/* Reduced padding for the container too */}
      <div className="resume-content p-0">
        <ReactMarkdown>{content}</ReactMarkdown>
      </div>

      <div className="mt-6 pt-4 border-t border-gray-300 text-center text-[8px] text-gray-400">
        Generated by Polaris AI
      </div>
    </div>
  );
}
